# JavaScript CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-javascript/ for more details.
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  node_v12:
    working_directory: "~/repo"
    docker:
      - image: "cimg/node:12.22.4-browsers"
    steps:
      - browser-tools/install-browser-tools
      - "checkout"
      - restore_cache:
          key: 'node-12.22-browsers-node-modules-{{ checksum "package.json" }}'
      - run:
          name: "Install packages"
          command: "npm ci"
      - save_cache:
          key: 'node-12.22-browsers-node-modules-{{ checksum "package.json" }}'
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test && npm run coverage"
  node_v10:
    working_directory: "~/repo"
    docker:
      - image: "cimg/node:10.24.1-browsers"
    steps:
      - browser-tools/install-browser-tools
      - "checkout"
      - restore_cache:
          key: 'node-10.24-browsers-node-modules-{{ checksum "package.json" }}'
      - run:
          name: "Install packages"
          command: "npm ci"
      - save_cache:
          key: 'node-10.24-browsers-node-modules-{{ checksum "package.json" }}'
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test"
workflows:
  version: 2
  build:
    jobs:
      - "node_v12"
      - "node_v10"
