# JavaScript CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-javascript/ for more details.
# image lists https://circleci.com/docs/2.0/docker-image-tags.json
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  node_v12:
    working_directory: "~/repo"
    docker:
      - image: "cimg/node:12.22.7-browsers"
    steps:
      - browser-tools/install-browser-tools
      - "checkout"
      - restore_cache:
          key: 'node-12.22-browsers-node-modules-{{ checksum "package.json" }}'
      - run:
          name: "Install pnpm"
          command: "sudo npm install -g pnpm"
      - run:
          name: "Install packages"
          command: "pnpm i"
      - save_cache:
          key: 'node-12.22-browsers-node-modules-{{ checksum "package.json" }}'
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test && npm run coverage"
  node_v14:
    working_directory: "~/repo"
    docker:
      - image: "cimg/node:14.10-browsers"
    steps:
      - browser-tools/install-browser-tools
      - "checkout"
      - restore_cache:
          key: 'node:14.10-browsers-node-modules-{{ checksum "package.json" }}'
      - run:
          name: "Install pnpm"
          command: "sudo npm install -g pnpm"
      - run:
          name: "Install packages"
          command: "pnpm i"
      - save_cache:
          key: 'node:14.10-browsers-node-modules-{{ checksum "package.json" }}'
          paths:
            - "node_modules"
      - run:
          name: "Execute linters"
          command: "npm run lint"
      - run:
          name: "Execute tests"
          command: "npm test"
workflows:
  version: 2
  build:
    jobs:
      - "node_v12"
      - "node_v14"
